In [53]:
# shell

# cd, mkdir, rm, ls, touch, cat, mv, chmod, nano, vim
# wc, sort, cut, grep, uniq, paste, tr, sed
# if, for, while
# |, >, >>


In [54]:
#!!

# Count the total number of lines in the file
# sort the file by scores in descending order
# extract names and display only the top names based on their score

! wc -l 'data.txt'



       5 data.txt


In [55]:
! sort -t' ' -k2 -nr 'data.txt'

Alice 92
Eve 91
Alice 90
Bob 88
John 85
Bob 72


In [56]:
# there are duplicates
! sort -t' ' -k2 -nr 'data.txt' | cut -d' ' -f1 | head -n3

Alice
Eve
Alice


In [57]:
# without duplicates
! sort -t' ' -k2,2 -nr 'data.txt' | cut -d' ' -f1 | head -n3 

Alice
Eve
Alice


In [58]:
### python

In [59]:
# data types: int, str, float, bool
# data structures: list, tuple, set, dict
# iterator, generators
# lambda, functionsm sum, max, sorted, min, filter, map
# exceptions
# classes

In [60]:
### exercise
data = ['alb3', 'x2z5', 'c9d', 'b4a', 'm2n3']
# sort data based on the digits

sorted(data, key = lambda t: sum([int(c) for c in t if c.isdigit()]))

['alb3', 'b4a', 'm2n3', 'x2z5', 'c9d']

In [61]:
# given this list:
L = [10, 7, 8, 8, 9, 12, 14, 5]
# find the second largest value

sorted(set(L), reverse = True)[1]

12

In [62]:
# flatten the following list
L = [[1,2,3], [4,5,6], [7,8]]

[i for s in L for i in s]

[1, 2, 3, 4, 5, 6, 7, 8]

In [63]:
# reverse the following dictinonary (swap keys and values)

d = {'james': 10, 'mike': 20, 112: 500, 'sarah': 70}


dict([(v,k) for k,v in d.items()])
# or
{v:k for k,v in d.items()}

{10: 'james', 20: 'mike', 500: 112, 70: 'sarah'}

In [64]:
# find palindromes

words = ['madam', 'racecar', 'hello', 'world', 'refer']
[w for w in words if w[::-1] == w]
# or
list(filter(lambda w: w==w[::-1], words))

['madam', 'racecar', 'refer']

In [65]:
# find all anagrams of a given word
word = 'listen'
list_of_words = ['enlist', 'google', 'inlets', 'banana', 'silent']

[i for i in list_of_words if sorted(i) == sorted(word)]

['enlist', 'inlets', 'silent']

In [66]:
### regular expressions

In [72]:
# exercise
# using regular expression, extract all hashtags from a tweet
tweet = 'loving the #python and #regex exercises!'

import re

re.findall(r'#\w+', tweet)


['#python', '#regex']

In [80]:
# using re, extract all possible floats from a given text
text = 'the values are 3.14, -0.99, 1.2 and 42.0' 

re.findall(r'-?\d+.\d+', text)

# have to do the \d+.\d as if you don't it will split umbers that have . between them
# the -?

['3.14', '-0.99', '1.2', '42.0']

In [81]:
# files (text, binary)
# webscraping
# numpy arrays


In [89]:
import numpy as np

a = np.arange(20).reshape(5,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [86]:
# total sum of values

a.sum
# or
np.sum(a)

np.int64(190)

In [87]:
# total sum of cols or rows
# axis = 0 --> column-wise sum (sum of all rows in a column)
# axis = 1 --> row-wise sum (sum of all columns in a row)

np.sum(a, axis = 1)



array([ 6, 22, 38, 54, 70])

In [90]:
# find the maximum value of each row in an array
# axis = 1 will find the max of each row, as it goes through all columns in 1 row
np.max(a, axis = 1)

array([ 3,  7, 11, 15, 19])

In [100]:
# exercise
# create an array (10, 10) of zeros surrounded with ones

b = np.zeros((5,5))
b[:,[0,-1]] = 1
b[[0,-1], :] = 1
b


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])