In [121]:
from bs4 import BeautifulSoup
import requests
import re
from datetime import datetime

In [122]:
"""
url = 'https://www.bbc.com/'

response = requests.get(url)
data = response.text

soup = BeautifulSoup(data)
text = soup.find_all('h2')

news = [t.text for t in soup.find_all('h2', {'class': 'sc-87075214-3 eywmDE'})]

f = open(str(datetime.now()) + '.txt', 'w')
f.write('\n'.join(news))
f.close()
"""

"\nurl = 'https://www.bbc.com/'\n\nresponse = requests.get(url)\ndata = response.text\n\nsoup = BeautifulSoup(data)\ntext = soup.find_all('h2')\n\nnews = [t.text for t in soup.find_all('h2', {'class': 'sc-87075214-3 eywmDE'})]\n\nf = open(str(datetime.now()) + '.txt', 'w')\nf.write('\n'.join(news))\nf.close()\n"

In [123]:
#


In [124]:
class person:
    # constructor
    def __init__(self, n='none', a=0):
        self.name = n
        self.age = a
    
    # string representation
    def __str__(self):
        return 'I am a person: my name is: ' + self.name + ', and my age is: ' + str(self.age)

In [125]:
p1 = person()
p2 = person('james', 25)

In [126]:
print(p1)

I am a person: my name is: none, and my age is: 0


### Numpy


In [127]:
import numpy as np

In [128]:
# creating arrays

a = np.array([10,20,30,40])

np.arange(2,10,.5)                  # np.arange(start, end, step)

np.linspace(2,10,50)                # np.linspace(start, end, # of values)

np.ones(10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [129]:
# shape

a = np.array([10,20,30,40,50,60])
a.shape
a.reshape(2,3)                              # creates a copy, does not reshape
# another way of reshaping
a.shape = [2,3]


In [130]:
# array vs list
L = [10,20,30,40,50,60,'hasan']
a = np.array([10,20,30,40,50,60])       # cannot have more than 1 datatype

# returns type of data inside array
a.dtype
# returns type of list/array
type(a)


numpy.ndarray

In [131]:
# arithmetic operations
# when doing operations such as +, -, /, * on a numpy array
# it will do the operation on every item in the array
# regular list will not do that
# same with comparisons, only with array not lists

L = [10,20,30,40,50,60]
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([10,20,30,40,50,60])
a3 = np.array([True, False, True])
a4 = np.array([False, False, True])

In [132]:
a1 * 10

array([100, 200, 300, 400, 500, 600])

In [133]:
a1+a2           # add each of the elements to the other in respective position
a1*a2           # have to be same length

array([ 100,  400,  900, 1600, 2500, 3600])

In [134]:
# same with comparisons, only with array not lists

a1 == 30
a1 == a2
a1 > a2

# check if all values are True
(a1 == a2).all()
# check if any values are True
(a1 == a2).any()

np.True_

In [135]:
# same with logiccal operators &, ^, ~, if they contain booleans

# negate all elements in a3
~a3

# does them element wise, so if like the following code
a3&a4
# will compare each element in the same place, and do the operation between them

array([False, False,  True])

In [136]:
# functions
# np.mean(), np.median, std, var, sum

