In [206]:
from bs4 import BeautifulSoup
import requests
import re
from datetime import datetime

In [207]:
"""
url = 'https://www.bbc.com/'

response = requests.get(url)
data = response.text

soup = BeautifulSoup(data)
text = soup.find_all('h2')

news = [t.text for t in soup.find_all('h2', {'class': 'sc-87075214-3 eywmDE'})]

f = open(str(datetime.now()) + '.txt', 'w')
f.write('\n'.join(news))
f.close()
"""

"\nurl = 'https://www.bbc.com/'\n\nresponse = requests.get(url)\ndata = response.text\n\nsoup = BeautifulSoup(data)\ntext = soup.find_all('h2')\n\nnews = [t.text for t in soup.find_all('h2', {'class': 'sc-87075214-3 eywmDE'})]\n\nf = open(str(datetime.now()) + '.txt', 'w')\nf.write('\n'.join(news))\nf.close()\n"

In [208]:
# topic switch


In [209]:
class person:
    # constructor
    def __init__(self, n='none', a=0):
        self.name = n
        self.age = a
    
    # string representation
    def __str__(self):
        return 'I am a person: my name is: ' + self.name + ', and my age is: ' + str(self.age)

In [210]:
p1 = person()
p2 = person('james', 25)

In [211]:
print(p1)

I am a person: my name is: none, and my age is: 0


### Numpy


In [212]:
import numpy as np

In [213]:
# creating arrays

a = np.array([10,20,30,40])

np.arange(2,10,.5)                  # np.arange(start, end, step)

np.linspace(2,10,50)                # np.linspace(start, end, # of values)

np.ones(10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [214]:
# shape

a = np.array([10,20,30,40,50,60])
a.shape
a.reshape(2,3)                              # creates a copy, does not reshape
# another way of reshaping
a.shape = [2,3]


In [215]:
# array vs list
L = [10,20,30,40,50,60,'hasan']
a = np.array([10,20,30,40,50,60])       # cannot have more than 1 datatype

# returns type of data inside array
a.dtype
# returns type of list/array
type(a)


numpy.ndarray

In [216]:
# arithmetic operations
# when doing operations such as +, -, /, * on a numpy array
# it will do the operation on every item in the array
# regular list will not do that
# same with comparisons, only with array not lists

L = [10,20,30,40,50,60]
a1 = np.array([10,20,30,40,50,60])
a2 = np.array([10,20,30,40,50,60])
a3 = np.array([True, False, True])
a4 = np.array([False, False, True])

In [217]:
a1 * 10

array([100, 200, 300, 400, 500, 600])

In [218]:
a1+a2           # add each of the elements to the other in respective position
a1*a2           # have to be same length

array([ 100,  400,  900, 1600, 2500, 3600])

In [219]:
# same with comparisons, only with array not lists

a1 == 30
a1 == a2
a1 > a2

# check if all values are True
(a1 == a2).all()
# check if any values are True
(a1 == a2).any()

np.True_

In [220]:
# same with logiccal operators &, ^, ~, if they contain booleans

# negate all elements in a3
~a3

# does them element wise, so if like the following code
a3&a4
# will compare each element in the same place, and do the operation between them

array([False, False,  True])

In [221]:
# functions
# np.mean(), np.median, std, var, sum, max, min, argmax, argmin, argsort

# value of min value
np.min(a1)
# position of min value
np.argmin(a1)

# gives you positions of where they should be when sorted
np.argsort(a1)

# so in the example belowm it will give you 1 at position zero, meaning
# that the element in position 1 in original array is the first in sorted
a5 = np.array([100,20,300,40,500,60])
np.argsort(a5)

array([1, 3, 5, 0, 2, 4])

In [222]:
# indexing

a = np.array([10,20,30,40,50,60]).reshape(2,3)
a

array([[10, 20, 30],
       [40, 50, 60]])

In [223]:
# both the same for now
a[0][1]         # a[row][rows from slice]
a[0,1]          # a[row, col]



np.int64(20)

In [224]:
# slicing
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [225]:
a[:, 1]                 # all rows in col 1
a[:, [1,3]]             # all rows in col 1 and 3
a[[0,-1], :]            # all columns in first and last row
a[:, [0,-1]]            # all rows in first and last col

# usually the same but not always
# the following 2 are not the same
a[:][0]                 # first row
a[:, 0]                 # all rows, first column

array([ 0,  5, 10, 15])

In [ ]:
# fancy indexing

a < 10                      # gives you boolean on each variable compared to 10

mask_array = a < 10         # stroes an array
mask_array

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [229]:
a[mask_array]               # when using that, it does indexing for you
                            # find all the values that fir the condition
                            # same as doing a[a<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [231]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
a = np.arange(20).reshape(4,5)
b = np.arange(10,30).reshape(4,5)
c = np.arange(20,40).reshape(4,5)

In [235]:
# give me all values that correspond to position where it satisfies original condition
c[b-a==10]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

In [242]:
import matplotlib.pyplot as plt

im = plt.imread('logo.jpg').astype(int)
print(im)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 ...

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  ...
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
